version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-2
    IMAGE_REPO_NAME: dukbill-app
    CONTAINER_NAME: dukbill-container-1

phases:
  pre_build:
    commands:
      - set -eu
      - echo "== Resolve account & repo URI =="
      - echo "random comment for commit test"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - COMMIT_SHA=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)
      - IMAGE_TAG=${IMAGE_TAG:-$COMMIT_SHA}
      # Persist for later phases
      - printf 'REPOSITORY_URI=%s\nIMAGE_TAG=%s\n' "$REPOSITORY_URI" "$IMAGE_TAG" > "$CODEBUILD_SRC_DIR/.vars"
      - echo "== Login to ECR =="
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - echo "== Ensure ECR repo exists =="
      - aws ecr describe-repositories --repository-names "$IMAGE_REPO_NAME" >/dev/null 2>&1 || aws ecr create-repository --repository-name "$IMAGE_REPO_NAME" >/dev/null

  build:
    commands:
      - set -eu
      - . "$CODEBUILD_SRC_DIR/.vars"   # POSIX source
      - echo "== Build image from Backend/ =="
      - cd Backend
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} -t ${REPOSITORY_URI}:latest .

  post_build:
    commands:
      - set -eu
      - . "$CODEBUILD_SRC_DIR/.vars"
      - echo "== Push images =="
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest || true
      - echo "== Write imagedefinitions.json at repo root =="
      - printf '[{"name":"%s","imageUri":"%s:%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI" "$IMAGE_TAG" > "$CODEBUILD_SRC_DIR/imagedefinitions.json"
      - echo "imagedefinitions.json:" && cat "$CODEBUILD_SRC_DIR/imagedefinitions.json"

artifacts:
  files:
    - imagedefinitions.json
